name: Deploy React to GitHub Pages
on:
  push:
    branches: [main] # וודא שזה שם הענף הראשי שלך
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # אם אתה משתמש ב-Vite, שנה ל-dist
          branch: gh-pages
